// Furniture the user brings in besides what was cut out of the room photo: a clean product photo
// for a detected piece, new pieces generated from the user's own photos, and library pieces.
import { bindings } from "./storage";
import { balances } from "./providers";
import { enqueue } from "./jobs";
import { BUDGET_USED_SQL, budgetLimit, estimate } from "./job-budget";
import { catalogItem } from "../catalog";
import { MAX_ITEMS, type Dims, type Item, type Project } from "../types";
import { say, type Lang } from "./say";
import { reusableModel } from "./demo";

const KINDS = ["bed", "desk", "cabinet", "chair", "sofa", "pendant", "other"];
export const MAX_BATCH = 8;
/** A request body as parsed from JSON: every field is checked before use. */
type Body = Record<string, unknown>;

export function readDims(v: unknown): Dims {
  const o = (v ?? {}) as Partial<Record<keyof Dims, unknown>>;
  const dims = { w: Number(o.w), d: Number(o.d), h: Number(o.h) };
  if (Object.values(dims).some((n) => !Number.isFinite(n) || n < 5 || n > 400))
    throw say("尺寸请填写 5–400 厘米之间的数字。", "Sizes must be numbers from 5 to 400 cm.");
  return dims;
}
/** An upload of this project, under the given role, that Tripo can read (PNG or JPEG). */
async function ownPhoto(p: Project, key: unknown, role: string) {
  const photo = String(key ?? "");
  const head = photo.startsWith(`${p.id}/uploads/${role}-`) ? await bindings().bucket.head(photo) : null;
  if (!head) throw say("照片不属于这个空间，请重新上传。", "That photo isn't part of this space. Please upload it again.");
  if (!["image/png", "image/jpeg"].includes(head.httpMetadata?.contentType ?? ""))
    throw say("照片需要是 PNG 或 JPEG，请重新上传。", "The photo needs to be a PNG or JPEG. Please upload it again.");
  return photo;
}
const point = (v: unknown): Item["position"] | null =>
  Array.isArray(v) && v.length === 3 && v.every((n) => typeof n === "number" && Number.isFinite(n) && Math.abs(n) <= 50)
    ? [v[0], v[1], v[2]]
    : null;

/** Review step: a clean photo and/or real size for one detected piece. `null` clears a field. */
export async function setFurnitureInput(p: Project, b: Body) {
  const id = String(b.candidate ?? "");
  if (p.mode !== "real" || p.stage !== "review" || p.branch !== "edit" || !p.cutouts?.[id])
    throw say("请先完成预览，再为家具补充照片和尺寸。", "Finish the preview first, then add photos and sizes for the furniture.");
  if (b.photo === null) delete p.productPhotos?.[id];
  else if (b.photo !== undefined) p.productPhotos = { ...p.productPhotos, [id]: await ownPhoto(p, b.photo, "product-photo-" + id) };
  if (b.dims === null) delete p.furnitureDims?.[id];
  else if (b.dims !== undefined) p.furnitureDims = { ...p.furnitureDims, [id]: readDims(b.dims) };
  return p;
}

/** New pieces from the user's own photos, each generated by Tripo. The note says when only part was submitted. */
export async function addFurniture(p: Project, user: string, b: Body, lang: Lang = "zh") {
  if (p.mode !== "real") throw say("示例房间不生成新家具，可以从家具库里挑选。", "The sample room doesn't generate new furniture. Pick from the library instead.");
  const list: Body[] = Array.isArray(b.furniture) ? b.furniture.map((f) => (f ?? {}) as Body) : [];
  if (!list.length) throw say("请至少添加一件家具。", "Add at least one piece.");
  if (list.length > MAX_BATCH) throw say(`一次最多添加 ${MAX_BATCH} 件家具。`, `Up to ${MAX_BATCH} pieces at a time.`);
  if (p.items.length + list.length > MAX_ITEMS) throw say(`一个空间最多放 ${MAX_ITEMS} 件家具。`, `A space holds up to ${MAX_ITEMS} pieces.`);
  if (b.approved !== true) throw say("请先确认预计消耗的积分。", "Confirm the estimated credits first.");
  const pieces = [];
  for (const f of list) {
    const name = String(f.name ?? "").trim().slice(0, 24);
    if (!name) throw say("请为每件家具填写名称。", "Give every piece a name.");
    pieces.push({
      name,
      kind: KINDS.includes(String(f.kind)) ? String(f.kind) : "other",
      dims: readDims(f.dims),
      image: await ownPhoto(p, f.image, "add-furniture"),
      // A photo that was already turned into a model gets that model back, free.
      reuse: await reusableModel(user, String(f.image), typeof f.print === "string" ? f.print : undefined),
    });
  }
  const added: string[] = [];
  for (const f of pieces.filter((f) => f.reuse)) {
    const id = crypto.randomUUID();
    p.items.push({
      id, name: f.name, kind: f.kind, status: "ready",
      position: [0, p.floor.height, 0], rotation: 0, scale: 1,
      height: f.dims.h / 100, dims: f.dims, source: "upload", model: f.reuse!.model, thumbnail: f.reuse!.thumbnail,
    });
    added.push(id);
  }
  const reused = added.length;
  const toGenerate = pieces.filter((f) => !f.reuse);
  const reuseNote = reused
    ? lang === "en"
      ? `${reused} ${reused === 1 ? "photo was" : "photos were"} already made into 3D, so ${reused === 1 ? "its model was" : "their models were"} reused with no credits spent.`
      : `${reused} 张照片之前已生成过 3D 模型，直接复用，未消耗积分。`
    : "";
  if (!toGenerate.length) return { note: reuseNote, added };
  // The whole batch must fit the local budget before anything is submitted.
  const cost = estimate("furniture") * toGenerate.length;
  const used = await bindings().db.prepare(`SELECT ${BUDGET_USED_SQL} AS used`).bind("furniture", "furniture").first<{ used: number }>();
  if ((used?.used ?? 0) + cost > budgetLimit("furniture")) throw say("已达到本地生成预算上限；这不是服务商余额不足。", "The local generation budget is used up (this is not the provider's balance).");
  const bal = await balances();
  if (bal.tripo.error || !Number.isFinite(bal.tripo.data?.balance) || bal.tripo.data.balance < cost)
    throw say(bal.tripo.error || "Tripo 可用积分不足。", bal.tripo.errorEn || "Not enough Tripo credits.");
  let note = reuseNote;
  for (const f of toGenerate) {
    const id = crypto.randomUUID();
    try {
      await enqueue(p, user, "furniture", id, { image: f.image });
    } catch (e) {
      const sent = toGenerate.indexOf(f);
      note = (note ? note + (lang === "en" ? " " : "") : "") + (lang === "en"
        ? `${sent} submitted; the rest were not: ${(e as { en?: string }).en ?? (e as Error).message}`
        : `已提交 ${sent} 件，其余未提交：${(e as Error).message}`);
      break;
    }
    p.items.push({
      id, name: f.name, kind: f.kind, status: "queued",
      position: [0, p.floor.height, 0], rotation: 0, scale: 1,
      height: f.dims.h / 100, dims: f.dims, source: "upload",
    });
    added.push(id);
  }
  return { note, added };
}

/** A library piece: its model is already prepared, so nothing is generated or charged. */
export function addCatalogItem(p: Project, b: Body) {
  const c = catalogItem(String(b.catalogId ?? ""));
  if (!c?.model || !c.modelHeight) throw say("家具库里没有这件家具。", "That piece isn't in the library.");
  if (p.mode === "real" && !p.room) throw say("先生成或导入 3D 房间，再从家具库挑选。", "Generate or import the 3D room first, then pick from the library.");
  if (p.items.length >= MAX_ITEMS) throw say(`一个空间最多放 ${MAX_ITEMS} 件家具。`, `A space holds up to ${MAX_ITEMS} pieces.`);
  // Dropped straight into the room: placed where it was dropped.
  const at = b.position === undefined ? null : point(b.position);
  if (b.position !== undefined && !at) throw say("放置位置无效。", "That spot isn't valid.");
  // The turn that squares it with the room's walls, worked out by the page; anything else is 0.
  const turn = at && typeof b.rotation === "number" && Number.isFinite(b.rotation) && Math.abs(b.rotation) <= 2 * Math.PI ? b.rotation : 0;
  const item: Item = {
    id: crypto.randomUUID(),
    name: c.name,
    kind: c.kind,
    status: at ? "placed" : "ready",
    position: at ?? [0, p.floor.height, 0],
    rotation: turn,
    scale: 1,
    height: c.modelHeight,
    dims: c.dims,
    model: c.model,
    thumbnail: c.image,
    source: "catalog",
    catalogId: c.id,
  };
  p.items.push(item);
  return item;
}
