// Furniture the user brings in besides what was cut out of the room photo: a clean product photo
// for a detected piece, new pieces generated from the user's own photos, and library pieces.
import { bindings } from "./storage";
import { balances } from "./providers";
import { enqueue } from "./jobs";
import { BUDGET_USED_SQL, budgetLimit, estimate } from "./job-budget";
import { catalogItem } from "../catalog";
import { MAX_ITEMS, type Dims, type Item, type Project } from "../types";

const KINDS = ["bed", "desk", "cabinet", "chair", "sofa", "other"];
export const MAX_BATCH = 8;
/** A request body as parsed from JSON: every field is checked before use. */
type Body = Record<string, unknown>;

export function readDims(v: unknown): Dims {
  const o = (v ?? {}) as Partial<Record<keyof Dims, unknown>>;
  const dims = { w: Number(o.w), d: Number(o.d), h: Number(o.h) };
  if (Object.values(dims).some((n) => !Number.isFinite(n) || n < 5 || n > 400))
    throw Error("尺寸请填写 5–400 厘米之间的数字。");
  return dims;
}
/** An upload of this project, under the given role, that Tripo can read (PNG or JPEG). */
async function ownPhoto(p: Project, key: unknown, role: string) {
  const photo = String(key ?? "");
  const head = photo.startsWith(`${p.id}/uploads/${role}-`) ? await bindings().bucket.head(photo) : null;
  if (!head) throw Error("照片不属于这个空间，请重新上传。");
  if (!["image/png", "image/jpeg"].includes(head.httpMetadata?.contentType ?? ""))
    throw Error("照片需要是 PNG 或 JPEG，请重新上传。");
  return photo;
}
const point = (v: unknown): Item["position"] | null =>
  Array.isArray(v) && v.length === 3 && v.every((n) => typeof n === "number" && Number.isFinite(n) && Math.abs(n) <= 50)
    ? [v[0], v[1], v[2]]
    : null;

/** Review step: a clean photo and/or real size for one detected piece. `null` clears a field. */
export async function setFurnitureInput(p: Project, b: Body) {
  const id = String(b.candidate ?? "");
  if (p.mode !== "real" || p.stage !== "review" || p.branch !== "edit" || !p.cutouts?.[id])
    throw Error("请先完成预览，再为家具补充照片和尺寸。");
  if (b.photo === null) delete p.productPhotos?.[id];
  else if (b.photo !== undefined) p.productPhotos = { ...p.productPhotos, [id]: await ownPhoto(p, b.photo, "product-photo-" + id) };
  if (b.dims === null) delete p.furnitureDims?.[id];
  else if (b.dims !== undefined) p.furnitureDims = { ...p.furnitureDims, [id]: readDims(b.dims) };
  return p;
}

/** New pieces from the user's own photos, each generated by Tripo. The note says when only part was submitted. */
export async function addFurniture(p: Project, user: string, b: Body) {
  if (p.mode !== "real") throw Error("示例房间不生成新家具，可以从家具库里挑选。");
  const list: Body[] = Array.isArray(b.furniture) ? b.furniture.map((f) => (f ?? {}) as Body) : [];
  if (!list.length) throw Error("请至少添加一件家具。");
  if (list.length > MAX_BATCH) throw Error(`一次最多添加 ${MAX_BATCH} 件家具。`);
  if (p.items.length + list.length > MAX_ITEMS) throw Error(`一个空间最多放 ${MAX_ITEMS} 件家具。`);
  if (b.approved !== true) throw Error("请先确认预计消耗的积分。");
  const pieces = [];
  for (const f of list) {
    const name = String(f.name ?? "").trim().slice(0, 24);
    if (!name) throw Error("请为每件家具填写名称。");
    pieces.push({
      name,
      kind: KINDS.includes(String(f.kind)) ? String(f.kind) : "other",
      dims: readDims(f.dims),
      image: await ownPhoto(p, f.image, "add-furniture"),
    });
  }
  // The whole batch must fit the local budget before anything is submitted.
  const cost = estimate("furniture") * pieces.length;
  const used = await bindings().db.prepare(`SELECT ${BUDGET_USED_SQL} AS used`).bind("furniture", "furniture").first<{ used: number }>();
  if ((used?.used ?? 0) + cost > budgetLimit("furniture")) throw Error("已达到本地生成预算上限；这不是服务商余额不足。");
  const bal = await balances();
  if (bal.tripo.error || !Number.isFinite(bal.tripo.data?.balance) || bal.tripo.data.balance < cost)
    throw Error(bal.tripo.error || "Tripo 可用积分不足。");
  let note = "";
  const added: string[] = [];
  for (const f of pieces) {
    const id = crypto.randomUUID();
    try {
      await enqueue(p, user, "furniture", id, { image: f.image });
    } catch (e) {
      note = `已提交 ${pieces.indexOf(f)} 件，其余未提交：${(e as Error).message}`;
      break;
    }
    p.items.push({
      id, name: f.name, kind: f.kind, status: "queued",
      position: [0, p.floor.height, 0], rotation: 0, scale: 1,
      height: f.dims.h / 100, dims: f.dims, source: "upload",
    });
    added.push(id);
  }
  return { note, added };
}

/** A library piece: its model is already prepared, so nothing is generated or charged. */
export function addCatalogItem(p: Project, b: Body) {
  const c = catalogItem(String(b.catalogId ?? ""));
  if (!c?.model || !c.modelHeight) throw Error("家具库里没有这件家具。");
  if (p.mode === "real" && !p.room) throw Error("先生成或导入 3D 房间，再从家具库挑选。");
  if (p.items.length >= MAX_ITEMS) throw Error(`一个空间最多放 ${MAX_ITEMS} 件家具。`);
  // Dropped straight into the room: placed where it was dropped.
  const at = b.position === undefined ? null : point(b.position);
  if (b.position !== undefined && !at) throw Error("放置位置无效。");
  const item: Item = {
    id: crypto.randomUUID(),
    name: c.name,
    kind: c.kind,
    status: at ? "placed" : "ready",
    position: at ?? [0, p.floor.height, 0],
    rotation: 0,
    scale: 1,
    height: c.modelHeight,
    dims: c.dims,
    model: c.model,
    thumbnail: c.image,
    source: "catalog",
    catalogId: c.id,
  };
  p.items.push(item);
  return item;
}
